"""
    Global variables
"""

from google.cloud import bigquery

COUNTRIES_DATA = {
    "AR": "Argentina",
    "AU": "Australia",
    "AT": "Austria",
    "BY": "Belarus",
    "BE": "Belgium",
    "BO": "Bolivia",
    "BR": "Brazil",
    "BG": "Bulgaria",
    "CA": "Canada",
    "CL": "Chile",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "EE": "Estonia",
    "FI": "Finland",
    "FR": "France",
    "DE": "Germany",
    "GR": "Greece",
    "GT": "Guatemala",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IT": "Italy",
    "JP": "Japan",
    "KZ": "Kazakhstan",
    "LV": "Latvia",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MY": "Malaysia",
    "MX": "Mexico",
    "MA": "Morocco",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NG": "Nigeria",
    "NO": "Norway",
    "PK": "Pakistan",
    "PA": "Panama",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "SA": "Saudi Arabia",
    "SG": "Singapore",
    "SK": "Slovakia",
    "ZA": "South Africa",
    "KR": "South Korea",
    "ES": "Spain",
    "SE": "Sweden",
    "CH": "Switzerland",
    "TW": "Taiwan",
    "TH": "Thailand",
    "TR": "Turkey",
    # "AE": "United Emirates",
    "GB": "United Kingdom",
    "US": "USA",
    "UA": "Ukraine",
    "UY": "Uruguay",
    "VE": "Venezuela",
    "VN": "Vietnam",
}

schemas = {
    "top_tracks": [
        bigquery.SchemaField("track_id", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("track_name", "STRING", mode="NULLABLE"),
        bigquery.SchemaField("added_at", "TIMESTAMP", mode="NULLABLE"),
        bigquery.SchemaField("album_id", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("artist_id", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("playlist_id", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("popularity", "INTEGER", mode="NULLABLE"),
        bigquery.SchemaField("preview_url", "STRING", mode="NULLABLE"),
        bigquery.SchemaField("is_explicit", "BOOLEAN", mode="NULLABLE"),
        bigquery.SchemaField("position", "INTEGER", mode="NULLABLE"),
    ],
    "albums": [
        bigquery.SchemaField("album_id", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("album_name", "STRING", mode="NULLABLE"),
        bigquery.SchemaField("release_date", "DATE", mode="NULLABLE"),
        bigquery.SchemaField("total_tracks", "INTEGER", mode="NULLABLE"),
        bigquery.SchemaField("album_type", "STRING", mode="NULLABLE"),
        bigquery.SchemaField("album_image_url", "STRING", mode="NULLABLE"),
    ],
    "artists": [
        bigquery.SchemaField("artist_id", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("artist_name", "STRING", mode="NULLABLE"),
        bigquery.SchemaField("artist_url", "STRING", mode="NULLABLE"),
        bigquery.SchemaField("genres", "STRING", mode="NULLABLE"),
    ],
    "available_markets": [
        bigquery.SchemaField("track_id", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("market", "STRING", mode="REQUIRED"),
    ],
    "playlists": [
        bigquery.SchemaField("playlist_id", "STRING", mode="REQUIRED"),
        bigquery.SchemaField("playlist_name", "STRING", mode="NULLABLE"),
        bigquery.SchemaField("playlist_description", "STRING", mode="NULLABLE"),
        bigquery.SchemaField("playlist_owner", "STRING", mode="NULLABLE"),
    ],
}

VARIABLE_FILE = "/opt/airflow/config/spotify_api_ids.json"
