COUNTRIES_DATA = {
    "US": "USA",
    "GB": "United Kingdom",
    "FR": "France",
    "DE": "Germany",
    "IT": "Italy",
    "ES": "Spain",
    "BR": "Brazil",
    "CA": "Canada",
    "AU": "Australia",
    "NL": "Netherlands",
    "SE": "Sweden",
    "NO": "Norway",
    "FI": "Finland",
    "JP": "Japan",
    "MX": "Mexico",
    "AR": "Argentina",
    "CL": "Chile",
    "CO": "Colombia",
    "IN": "India",
    "ID": "Indonesia",
    "NZ": "New Zealand",
    "ZA": "South Africa",
    "SA": "Saudi Arabia",
    "AE": "UAE",
    "PH": "Philippines",
    "TR": "Turkey",
    "TH": "Thailand",
    "VN": "Vietnam",
    "SG": "Singapore",
    "MY": "Malaysia",
    "IE": "Ireland",
    "PT": "Portugal",
    "HU": "Hungary",
    "CZ": "Czech Republic",
    "SK": "Slovakia",
    "DK": "Denmark",
    "BE": "Belgium",
    "CH": "Switzerland",
    "AT": "Austria",
    "GR": "Greece",
    "RO": "Romania",
    "BG": "Bulgaria",
    "HR": "Croatia",
    "RS": "Serbia",
    "SI": "Slovenia",
    "EE": "Estonia",
    "LT": "Lithuania",
    "LV": "Latvia",
    "KR": "South Korea",
}

VARIABLE_FILE = "/opt/airflow/config/ids.json"